[package]
name = "ormox"
version = "0.1.0"
edition = "2021"

[dependencies]
ormox_core = {path = "./crates/ormox_core"}
ormox_derive = {path = "./crates/ormox_derive", optional = true}

[features]
default = ["derive"]
derive = ["dep:ormox_derive"]
