[package]
name = "ormox_test"
version = "0.1.0"
edition = "2021"

[dependencies]
ormox = { path = "../crates/ormox", features = ["derive", "default", "polodb"] }
polodb_core = "5.1.3"
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
